### ISSUE TITLE
增加 Gitee 镜像？

### ISSUE THREAD

**Issue by Sonic853** [Tree-Roots/VRChatPackages#1]
如题，目前国内部分地区不方便使用 Github，如果能架设 Gitee 镜像是最好不过了。

**Comment by Tree-Roots** [comment]
感谢您提交问题，但我无法注册 Gitee 帐户。
如果可以，您可以使用 Gitee 的存储库同步功能。

**Comment by Sonic853** [comment]
感谢回复，Gitee 仓库的同步功能是手动同步的，以及类似 workflow 的流水线功能似乎不是免费的，不知道能不能使用 Github 的 workflow 功能来同步到 Gitee 仓库

**Comment by Tree-Roots** [comment]
可以，你可以通过 [hub-mirror](https://github.com/yi-Xu-0100/hub-mirror) 来同步仓库到 Gitee 上。

**Comment by Sonic853** [comment]
已部署，目前看上去正常：
[VRChatPackagesSync2Gitee](https://github.com/Sonic853/VRChatPackagesSync2Gitee)
